name: adobe-client-php
type: php
docroot: .
php_version: "8.2"
webserver_type: apache-fpm
router_http_port: "8080"
router_https_port: "8443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - COMPOSER_MEMORY_LIMIT=-1



